### ISSUE TITLE
ユーザ情報更新APIの実装

### ISSUE THREAD

**Issue by tmyt** [locapos/docs#1]
locapos.com上に表示される名前を変更する機能の提供を検討中。

`/users/update` をエンドポイントし、次の機能を提供する。
- 表示名の変更

このエンドポイントは今後表示名以外の変更も許容できるような設計とする。

将来的に変更可能なパラメータが増えた場合を考慮し、次の2種類のインターフェースを検討している。
1. application/www-form-urlencoded 形式
2. JSON形式

どちらの場合でも変更したいパラメタのみ送信すればよい。現在その他のAPIはapplication/www-form-urlencoded形式でパラメタを受け付けているため、それにそろえるのであればapplication/www-form-urlencoded形式とするべきである。

どちらにするべきだろうか。

**Comment by ChiiAyano** [comment]
エンドポイントによって要求するデータ構造が変わるのはあまりよろしくないので統一するべきで、取り回しのしやすさ等を考えると `JSON` がよいかなと思いますが、
Mikaboshi がリリースされ一般利用者も使い始めている今、`urlencoded` から `JSON` に切り替える場合、しばらくの間両方を受けられるような仕組みを持たねばならないと考えると悩ましいところです。
その点を考えると、現状では `urlencoded` で進むのが正しいかなと思います。両方並走できるなら `JSON` にしてもいいんじゃねっていう具合です。

**Comment by hamache9821** [comment]
api v1(現行)はurlencodedで、v2はJSONで実装しちゃう感じはどうでしょうか。
個人的にはNode.jsから使う場合はJSONのほうがシリアル化が楽なのでJSON派なのですが。

**Comment by ChiiAyano** [comment]
いきなしv2爆誕っすね(；´∀｀)

**Comment by hamache9821** [comment]
GETの例でアレなんですけど、うちで作ってるやつだと、/api/hoge だと プレーンtextで /api/hoge.jsonだとjsonで、みたいな感じに拡張子で分けています。
メンテナンス性下がっちゃうから微妙な案なのですが。

**Comment by tmyt** [comment]
いまサーバはnodejsなのでぶっちゃけJSONのほうが楽なんですけど、走り出しちゃったしurlencodedなのかなぁ…と思ったり。
JSONだとブラウザとかcurlからデバッグめんどくさいし、v2が爆誕する頃にはJSONなのかなぁ…

**Comment by ChiiAyano** [comment]
今のところ `urlencoded` で実装進めるってところかしら

**Comment by tmyt** [comment]
とりあえずv1は`urlencoded`で進めましょう。インターフェースはこんな感じを予定。

## 引数

|  | 名前 | 値 |
| --- | --- | --- |
|  | screen_name | ページ上の表示名 |

更新したい情報の任意の1つ以上の組み合わせが必須。

## 戻り値

値が変更できた場合HTTP 200ステータスコードと共に`OK`の2バイト。
引数が何も設定されていなかった場合HTTP 403、認証情報が間違っていた場合HTTP 401をそれぞれ返す。

**Comment by ChiiAyano** [comment]
OK こっち対応進めます

**Comment by ChiiAyano** [comment]
`screen_name` が空の時、デフォルト値（ログインしたサービスに紐づく名前）に戻すことってできる？それとも認証しなおしで解決？

**Comment by tmyt** [comment]
あー　戻す方法がないし、認証しなおしてもトークンがExpireしてない限り戻らない、どうしようか

**Comment by tmyt** [comment]
引数の名前を
- username
- name
- screen_name

で揺れてる

**Comment by hamache9821** [comment]
＞初期値に戻す
内部的にdefault_usernameでも持っておくしかないのでは
＞引数の名前
nameだけだと将来なんか増えたときになんのnameなのかわからなくなりそうなのと、
他の引数も単語を_で区切ってるから screen_name でいいんじゃないかなあ

**Comment by tmyt** [comment]
screen_nameなのか、display_nameなのかってところか

**Comment by ChiiAyano** [comment]
僕も `screen_name` 派

**Comment by tmyt** [comment]
`screen_name`で決着。内部的には`default_username`を持つこととして、`screen_name`に空文字列を指定してリクエストすると`default_username`に書き戻る仕様にします。

**Comment by tmyt** [comment]
実装しました。ドキュメント更新します。

**Comment by tmyt** [comment]
ドキュメント更新、実装完了したのでクローズ。
