### ISSUE TITLE
locations/updateのheadingパラメタをオプションにする

### ISSUE THREAD

**Issue by tmyt** [locapos/docs#2]
locations/updateのheadingパラメタが現状必須項目となってるが、API利用者の利便性と使いやすさ向上のために、ここをオプションに変更したい。

また、headingパラメタを省略した場合はサーバ上に前回位置情報がある場合についてのみサーバ上でheadingを計算して格納するものとする。

これらの変更によってAPIの動作の変更を計画している。
- heading パラメタを省略した場合でも HTTP 200 OK を返却
- heading パラメタが省略された場合は前回位置情報に基づきサーバ側でheading パラメタを自動計算

加えて、現状ではheadingパラメタが0～360を超えた場合でも特にエラーとはしていないが、この場合の動作を次の2パターンで検討している。
1. 範囲外の場合はHTTP 403 エラーとする
2. 範囲外の場合は前回位置情報に基づいた自動計算値とする

**Comment by ChiiAyano** [comment]
heading の省略可能化とその際の挙動については問題ないと思います。
0 ～ 360 の範囲を超える値が渡ったときの挙動については、現状 Mikaboshi が -180 ～ 0 ～ 180 で送信しているので、もし変更する場合は正規化をクライアントで実装する必要がでてきそう
とはいえ正規化自体は実装済みなので、渡す値をそっちにすればいいだけだけども

**Comment by tmyt** [comment]
だとすると、範囲外は現状通り正規化して、値無しだった場合は自動計算値とするのがよいかな。

自動計算値かどうかを判定する真偽値を、レスポンスに乗せるようにするべきかしら？

**Comment by ChiiAyano** [comment]
自動計算値かどうかはあってもいいとは思うけど、必要かというと必要ないかなあとは思ったり。少なくともMikaboshiではそれによって状態を分けることはしないつもりですな

**Comment by tmyt** [comment]
現状の実装よくみたら負数渡すと矢印でないとおもうんでうが、Mikaboshiだめじゃないすか？

**Comment by ChiiAyano** [comment]
えー、 `Geocoordinate` の `Heading` そのまま流してて、ログ見ると負数使ってるように見えるんだけどなあ

**Comment by tmyt** [comment]
とりあえず範囲外は0-360に正規化するようにしておきました 😉

**Comment by tmyt** [comment]
自動計算値フラグはなくして、実装確定とします。

**Comment by tmyt** [comment]
ドキュメント反映したのでクローズ
